config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    resources :home

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"
      get "get_all_orders_report" => "orders#get_all_orders_report"
      get "seven_days_ago_report" => "orders#seven_days_ago_report"
      get "reports" => "reports#index"

      resources :products do
        collection do
          patch :sort
          get "sort_product" => "products#sort_product", as: "sort_product"
          get "sort_product_featured" => "products#sort_product_featured", as: "sort_product_featured"
        end
      end



      resources :categories
      resources :sub_categories
      resources :product_types
      resources :galleries
      resources :orders do
        collection do
          get "search" => "orders#search", vai: [:get, :post], as: :search
        end
      end
      resources :users
      resources :admins
      resources :line_items
      resources :settings, only: [:index, :new, :update, :create, :edit]

      get "testorder" => "orders#testorder"
    end

    resources :sub_categories, only: [:show]
    resources :categories, only: [:show]
    resources :wishlists
    resources :products do
      resources :reviews
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: 'users/passwords'
    }

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    resources :orders do
      delete "cancel/:id" => "line_items#cancel_item", as: "cancel_line_item"
      post "update_quantity/:id" => "line_items#update_quantity", as: "update_quantity"
    end
    resources :product_types, only: [:index, :show]
    resources :types, only: [:show]
    get 'profiles' => "orders#profile", :as => "profiles"
    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'
    get 'abouts' => "static_pages#about", :as => "abouts"
    get 'deliveries' => "static_pages#delivery", :as => "deliveries"
    get 'cancellation' => "static_pages#cancellation", :as => "cancellation"

    get 'cart' => "line_items#index"
    get 'history' => "line_items#history", :as => "history"
    resources :line_items, path: "/cart/items"
    get  'cart/checkout' => "orders#new", :as => "checkout"
    patch 'cart/checkout' => "orders#create"
    get 'under_construction' => "static_pages#under_construction", as: "under_construction"

end

app/models/gallery.rb
class Gallery < ApplicationRecord
    belongs_to :admin, optional: true

    # has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
    # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?, except: [:index]
  before_action :delivery_only?
  def index
    @gallery = current_admin.galleries.build
    @galleries = Gallery.all.order(id: :desc)
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new

  end

  def create
    @gallery = current_admin.galleries.build(galleries_params)
    if @gallery.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_galleries_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or category Duplicated"
        format.html { redirect_to admin_galleries_path }
        format.js { render template: "admin/galleries/gallery_error.js.erb" }
      end
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    if @gallery.update(galleries_params)
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_galleries_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or category Duplicated"
        format.html { redirect_to admin_galleries_path }
        format.js { render template: "admin/galleries/gallery_error.js.erb" }
      end
    end
  end

  def destroy
    @gallery = Gallery.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_galleries_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def delivery_only?
      unless !current_admin.delivery?
        unless @admin == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def galleries_params
      params.required(:gallery).permit!
    end
end

app/helpers/admin/galleries_helper.rb
module Admin::GalleriesHelper
end

app/views/admin/galleries/_edit.html.erb
<%=content_tag :div, class: "modal fade modal-slide-right", id: "edit_#{dom_id(@gallery, :modal)}" do%>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-12">
            <h5 class="m-b-0">Edit product</h5>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%=simple_form_for([:admin, @gallery], remote: true) do |f|%>
      <div class="modal-body overflow-auto">
        <div class="form-row">
          <div class="form-group col-md-12">
            <%=f.text_field :image, class: "form-control"%>
          </div>
          <div class="form-group col-md-12">
            <%=f.submit "Update", class: "btn btn-primary"%>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/admin/galleries/_gallery.html.erb
<tr class="delete_gallery_<%=gallery.id%>">
  <td id="data_<%=gallery.id%>">
    <%=gallery.id%>
  </td>
  <td>
    <%=time_ago(gallery.created_at)%>
  </td>
  <td class="text-center">
    <%=form_for([:admin, gallery], remote: true) do |f|%>
      <%=link_to admin_gallery_path(gallery), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
        View
      <%end%>
      <%=link_to edit_admin_gallery_path(gallery),id: "link_#{gallery.id}",class: "btn btn-primary", remote: true do %>
        Edit
      <% end %>
    <%end%>
  </td>
</tr>

app/views/admin/galleries/_gallery_form.html.erb
<%=simple_form_for([:admin, @gallery], remote: true) do |f|%>
  <div class="form-row">
    <div class="form-group col-md-12">
      <%=f.text_field :image, class: "form-control"%>
    </div>
    <div class="col-md-12">
       <div class="form-group">
          <label class="cstm-switch">
          <%=f.check_box :status, class: "cstm-switch-input"%>
          <span class="cstm-switch-indicator "></span>
          <span class="cstm-switch-description"> Status </span>
          </label>
       </div>
    </div>
     <div class="form-group col-md-12">
        <%=f.submit "Save User", class: "btn btn-primary"%>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
     </div>
  </div>
<%end%>

app/views/admin/galleries/_show.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "detail_#{dom_id(@gallery, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myLargeModalLabel">Large Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3>I'm large modal</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          Aspernatur, assumenda aut eaque eius error, eum expedita iusto nobis
          obcaecati, perspiciatis quae quos saepe similique! Iure non
          perspiciatis qui veniam vitae!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
<%end%>

app/views/admin/galleries/create.js.erb
$(".disabled").attr("disabled", false)
$("#gallery-errors").html(" ");
$("#gallery-success").html("<%= custom_flash_message%>");
$("#gallery-index").append("<%=escape_javascript render(@gallery)%>");

$(function() {
  $('.delete_gallery_<%=@gallery.id%>').submitOnCheck();
});

$('.delete_gallery_<%=@gallery.id%>').submitOnCheck();

app/views/admin/galleries/destroy.js.erb
$('.delete_gallery_<%=@gallery.id%>').remove();

app/views/admin/galleries/edit.js.erb
$('body').append('<%= j render partial: "admin/galleries/edit"%>');
$('#edit_<%= dom_id @gallery, :modal%>').modal('toggle');

$('tr').find('td:nth-child(1)').each(function(){
  if ($(this).text().trim() == "<%=@gallery.id%>") {
    $(this).parent().addClass("edit_row_<%=@gallery.id%>")
  }
});

app/views/admin/galleries/gallery_error.js.erb
$("#gallery-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/galleries/gallery_success.js.erb
$("#gallery-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/galleries/index.html.erb
<%=render "admin/shared/aside"%>
<main class="admin-main">
   <!--site header begins-->
   <%=render "admin/shared/header"%>
   <!--site header ends -->
   <section class="admin-content">
      <div class="container">
      <div class="row m-t-30">
         <div class="col-md-auto col">
            <div class="kanban-item" style="margin-bottom: 0px;">
               <a class="kanban-item-title btn btn-primary" style="color: #fff;">
               <i class="mdi mdi-plus-circle-outline"></i>
               Add Gallery
               </a>
            </div>
         </div>
      </div>
      <!-- Content -->
      <div class="row">
         <div class="col-md-12">
            <div class="card m-b-30 m-t-30">
               <div class="card-header">
                  <h5 class="m-b-0">
                     <i class="mdi mdi-checkbox-intermediate"></i> Galleries
                  </h5>
               </div>
               <div class="card-body">
                  <div class="table-responsive">
                     <table id="example" class="table table-hover align-td-middle">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Created_At</th>
                              <th class="text-center">Action</th>
                           </tr>
                        </thead>
                        <tbody id="gallery-index">
                           <%if @galleries.any?%>
                           <%= render @galleries%>
                           <%end%>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Modal -->
   </section>
</main>
<div class="modal fade modal-slide-right" id="kanbanItemModal" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <div class="row">
               <div class="col-md-12">
                  <h5 class="m-b-0">Create User</h5>
               </div>
            </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body overflow-auto">
            <div id="gallerys">
               <div id="gallery-errors"></div>
               <div id="gallery-success"></div>
               <%=render partial: "gallery_form", locals: {gallery: @gallery}%>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/admin/galleries/show.js.erb
$('body').append('<%= j render partial: "admin/galleries/show"%>');
$('#detail_<%= dom_id @gallery, :modal%>').modal('toggle');

app/views/admin/galleries/update.js.erb
$("#gallery-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");
$(".edit_row_<%=@gallery.id%>").find('td:nth-child(2)').text("<%=@gallery.id%>").next().text("<%=time_ago(@gallery.created_at)%>")