config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    resources :home

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"
      get "get_all_orders_report" => "orders#get_all_orders_report"
      get "seven_days_ago_report" => "orders#seven_days_ago_report"
      get "reports" => "reports#index"

      resources :products do
        collection do
          patch :sort
          get "sort_product" => "products#sort_product", as: "sort_product"
          get "sort_product_featured" => "products#sort_product_featured", as: "sort_product_featured"
        end
      end



      resources :categories
      resources :sub_categories
      resources :product_types
      resources :galleries
      resources :orders do
        collection do
          get "search" => "orders#search", vai: [:get, :post], as: :search
        end
      end
      resources :users
      resources :admins
      resources :line_items
      resources :settings, only: [:index, :new, :update, :create, :edit]

      get "testorder" => "orders#testorder"
    end

    resources :sub_categories, only: [:show]
    resources :categories, only: [:show]
    resources :wishlists
    resources :products do
      resources :reviews
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: 'users/passwords'
    }

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    resources :orders do
      delete "cancel/:id" => "line_items#cancel_item", as: "cancel_line_item"
      post "update_quantity/:id" => "line_items#update_quantity", as: "update_quantity"
    end
    resources :product_types, only: [:index, :show]
    resources :types, only: [:show]
    get 'profiles' => "orders#profile", :as => "profiles"
    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'
    get 'abouts' => "static_pages#about", :as => "abouts"
    get 'deliveries' => "static_pages#delivery", :as => "deliveries"
    get 'cancellation' => "static_pages#cancellation", :as => "cancellation"

    get 'cart' => "line_items#index"
    get 'history' => "line_items#history", :as => "history"
    resources :line_items, path: "/cart/items"
    get  'cart/checkout' => "orders#new", :as => "checkout"
    patch 'cart/checkout' => "orders#create"
    get 'under_construction' => "static_pages#under_construction", as: "under_construction"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception

  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :set_locale
  before_action :search_product
  before_action :set_order
  before_action :newOrder
  # respond_to :html, :xml, :json, :js

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number,:country_code,:role,:email,:password, :username, :avata])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :role, :email,:password,:password_confirmation,:current_password, :username, :avata])
  end

  def newOrder
    @new_order = Order.where("status = false AND sold_date")
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      if admin_signed_in?
        admin_dashboard_path
      else
        root_path
      end
    else
      super
    end
  end

  def set_locale
    locale = I18n.available_locales.include?(params[:locale].to_sym) ? params[:locale] : I18n.locale if params[:locale].present?
    I18n.locale = locale || I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge(options)
  end

  private

    def search_product
      @cart = @current_cart
    end

    def time_ago(time)
      time
    end

    def set_order
      @orders = Order.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end

  def logged_in_using_omniauth?
    session[:logged_in_using_omniauth].present?
  end

  def first_cap_letter(string)
    string.split(' ').map{ |w| w.capitalize }.join(' ')
  end

end

app/views/applications/_nav.html.erb
<!-- Top Menu Items -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="nav-wrap">
    <div class="mobile-only-brand pull-left">
      <div class="nav-header pull-left">
        <div class="logo-wrap">
          <a href="index-2.html">

          </a>
        </div>
      </div>
      <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block ml-20 pull-left" href="javascript:void(0);"><i class="ti-align-left"></i></a>
      <a id="toggle_mobile_search" data-toggle="collapse" data-target="#search_form" class="mobile-only-view" href="javascript:void(0);"><i class="zmdi zmdi-search"></i></a>
      <a id="toggle_mobile_nav" class="mobile-only-view" href="javascript:void(0);"><i class="ti-more"></i></a>
      <form id="search_form" role="search" class="top-nav-search collapse pull-left">
        <div class="input-group">
          <input type="text" name="example-input1-group2" class="form-control" placeholder="Search">
          <span class="input-group-btn">
          <button type="button" class="btn  btn-default"  data-target="#search_form" data-toggle="collapse" aria-label="Close" aria-expanded="true"><i class="zmdi zmdi-search"></i></button>
          </span>
        </div>
      </form>
    </div>
    <div id="mobile_only_nav" class="mobile-only-nav pull-right">
      <ul class="nav navbar-right top-nav pull-right">
        <li class="dropdown alert-drp">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="ti-bell top-nav-icon"></i>
              <span id="orders">
                <%= render partial: 'orders'%>
              </span>
          </a>
          <ul class="dropdown-menu alert-dropdown" data-dropdown-in="bounceIn" data-dropdown-out="bounceOut">
            <li>
              <div class="notification-box-head-wrap">
                <span class="notification-box-head pull-left inline-block">notifications</span>
                <a class="txt-danger pull-right clear-notifications inline-block" href="javascript:void(0)"> clear all </a>
                <div class="clearfix"></div>
                <hr class="light-grey-hr ma-0" />
              </div>
            </li>
            <li>
              <div class="streamline message-nicescroll-bar" id="lists_order">
                <%if @orders.any?%>
                  <%= render @orders%>
                <%end%>
              </div>
            </li>
            <li>
              <div class="notification-box-bottom-wrap">
                <hr class="light-grey-hr ma-0" />
                <a class="block text-center read-all" href="javascript:void(0)"> read all </a>
                <div class="clearfix"></div>
              </div>
            </li>
          </ul>
        </li>
        <li class="dropdown auth-drp">
          <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown">
            <%if current_admin.photo.present?%>
              <img src="<%=current_admin.photo%>" alt="user_auth" class="user-auth-img img-circle"/>
              <span class="user-online-status"></span>
            <%else%>
              <img src="https://hencework.com/theme/admintres/img/user1.png" alt="user_auth" class="user-auth-img img-circle"/>
              <span class="user-online-status"></span>
            <%end%>
          </a>
          <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="flipInX" data-dropdown-out="flipOutX">
            <li>
              <a href="profile.html"><i class="zmdi zmdi-account"></i><span>Profile</span></a>
            </li>
            <li>
              <a href="#"><i class="zmdi zmdi-card"></i><span>my balance</span></a>
            </li>
            <li>
              <a href="inbox.html"><i class="zmdi zmdi-email"></i><span>Inbox</span></a>
            </li>
            <li>
              <a href="#"><i class="zmdi zmdi-settings"></i><span>Settings</span></a>
            </li>

            <li class="divider"></li>
            <li>
              <%=link_to destroy_admin_session_path, method: :delete do%>
                <i class="zmdi zmdi-power"></i><span>Log Out</span>
              <%end%>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- /Top Menu Items -->

<!-- Left Sidebar Menu -->
<div class="fixed-sidebar-left">
  <ul class="nav navbar-nav side-nav nicescroll-bar">
    <li class="navigation-header">
      <span>Main</span>
      <hr/>
    </li>
      <li>
        <%=link_to admin_dashboard_path do%>
        <div class="pull-left"><i class="ti-dashboard mr-20"></i><span class="right-nav-text">Dashboard</span></div>
        <div class="clearfix"></div>
        <%end%>
      </li>
      <li>
        <%=link_to admin_admins_path do%>
          <div class="pull-left"><i class="ti-user mr-20"></i><span class="right-nav-text">Admins</span></div>
          <div class="pull-right"><i class="ti-angle-down"></i></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
      <li>
        <a href="javascript:void(0);" data-toggle="collapse" data-target="#ecom_dr">
          <div class="pull-left"><i class="ti-shopping-cart  mr-20"></i><span class="right-nav-text">Inventory</span></div>
          <div class="pull-right"><i class="ti-angle-down"></i></div>
          <div class="clearfix"></div>
        </a>
        <ul id="ecom_dr" class="collapse collapse-level-1">
          <li>
            <%=link_to "Category", admin_categories_path%>
          </li>
          <li>
            <%=link_to "Sub Category", admin_sub_categories_path%>
          </li>
          <li>
            <%=link_to "Product Type", admin_product_types_path%>
          </li>
          <li>
            <%=link_to "Gallery", admin_galleries_path%>
          </li>
          <li>
            <%=link_to "Products", admin_products_path%>
          </li>
        </ul>
      </li>
      <li>
        <%=link_to admin_orders_path do%>
          <div class="pull-left"><i class="ti-image mr-20"></i><span class="right-nav-text">Orders</span></div>
          <div class="pull-right"><i class="ti-angle-down"></i></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
      <li>
        <%=link_to admin_line_items_path do%>
          <div class="pull-left"><i class="ti-image mr-20"></i><span class="right-nav-text">Order Details </span></div>
          <div class="pull-right"><i class="ti-angle-down"></i></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
      <li>
        <%=link_to admin_users_path do%>
          <div class="pull-left"><i class="ti-user mr-20"></i><span class="right-nav-text">Customers</span></div>
          <div class="pull-right"><i class="ti-angle-down"></i></div>
          <div class="clearfix"></div>
        <%end%>
      </li>
  </ul>
</div>
<!-- /Left Sidebar Menu -->

app/views/applications/_setting.html.erb
<!-- Right Setting Menu -->
<div class="setting-panel">
  <ul class="right-sidebar nicescroll-bar pa-0">
    <li class="layout-switcher-wrap">
      <ul>
        <li>
          <span class="layout-title">Scrollable header</span>
          <span class="layout-switcher">
              <input type="checkbox" id="switch_3" class="js-switch"  data-color="ff6028" data-secondary-color="#dedede" data-size="small"/>
            </span>
          <h6 class="mt-30 mb-15">Sidebar colors</h6>
          <ul class="theme-option-wrap">
            <li id="theme-1"><i class="zmdi zmdi-check"></i></li>
            <li id="theme-2" class="active-theme"><i class="zmdi zmdi-check"></i></li>
          </ul>
          <h6 class="mt-30 mb-15">Topbar colors</h6>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-blue" value="navbar-top-blue">
            <label class="capitalize-font" for="navbar-top-blue"> blue </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-skyblue" value="navbar-top-skyblue">
            <label class="capitalize-font" for="navbar-top-skyblue"> skyblue </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-navyblue" checked value="navbar-top-navyblue">
            <label class="capitalize-font" for="navbar-top-navyblue"> navyblue </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-purple" value="navbar-top-purple">
            <label class="capitalize-font" for="navbar-top-purple"> purple </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-pink" value="navbar-top-pink">
            <label class="capitalize-font" for="navbar-top-pink"> pink </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-red" value="navbar-top-red">
            <label class="capitalize-font" for="navbar-top-red"> red </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-yellow" value="navbar-top-yellow">
            <label class="capitalize-font" for="navbar-top-yellow"> yellow </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-green" value="navbar-top-green">
            <label class="capitalize-font" for="navbar-top-green"> green </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-teal" value="navbar-top-teal">
            <label class="capitalize-font" for="navbar-top-teal"> teal </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-violet" value="navbar-top-violet">
            <label class="capitalize-font" for="navbar-top-violet"> violet </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-chrome" value="navbar-top-chrome">
            <label class="capitalize-font" for="navbar-top-chrome"> chrome </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-orange" value="navbar-top-orange">
            <label class="capitalize-font" for="navbar-top-orange"> orange </label>
          </div>
          <div class="radio mb-5">
            <input type="radio" name="radio-topbar-color" id="navbar-top-dark" value="navbar-top-dark">
            <label class="capitalize-font" for="navbar-top-dark"> dark </label>
          </div>
          <div class="radio mb-35">
            <input type="radio" name="radio-topbar-color" id="navbar-top-light" value="navbar-top-light">
            <label class="capitalize-font" for="navbar-top-light"> light </label>
          </div>
          <button id="reset_setting" class="btn  btn-warning btn-xs btn-outline btn-rounded mb-10">reset</button>
        </li>
      </ul>
    </li>
  </ul>
</div>
<button id="setting_panel_btn" class="btn btn-warning btn-circle setting-panel-btn shadow-2dp"><i class="zmdi zmdi-settings"></i></button>
<!-- /Right Setting Menu -->