config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    resources :home

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"
      get "get_all_orders_report" => "orders#get_all_orders_report"
      get "seven_days_ago_report" => "orders#seven_days_ago_report"
      get "reports" => "reports#index"

      resources :products do
        collection do
          patch :sort
          get "sort_product" => "products#sort_product", as: "sort_product"
          get "sort_product_featured" => "products#sort_product_featured", as: "sort_product_featured"
        end
      end



      resources :categories
      resources :sub_categories
      resources :product_types
      resources :galleries
      resources :orders do
        collection do
          get "search" => "orders#search", vai: [:get, :post], as: :search
        end
      end
      resources :users
      resources :admins
      resources :line_items
      resources :settings, only: [:index, :new, :update, :create, :edit]

      get "testorder" => "orders#testorder"
    end

    resources :sub_categories, only: [:show]
    resources :categories, only: [:show]
    resources :wishlists
    resources :products do
      resources :reviews
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: 'users/passwords'
    }

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    resources :orders do
      delete "cancel/:id" => "line_items#cancel_item", as: "cancel_line_item"
      post "update_quantity/:id" => "line_items#update_quantity", as: "update_quantity"
    end
    resources :product_types, only: [:index, :show]
    resources :types, only: [:show]
    get 'profiles' => "orders#profile", :as => "profiles"
    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'
    get 'abouts' => "static_pages#about", :as => "abouts"
    get 'deliveries' => "static_pages#delivery", :as => "deliveries"
    get 'cancellation' => "static_pages#cancellation", :as => "cancellation"

    get 'cart' => "line_items#index"
    get 'history' => "line_items#history", :as => "history"
    resources :line_items, path: "/cart/items"
    get  'cart/checkout' => "orders#new", :as => "checkout"
    patch 'cart/checkout' => "orders#create"
    get 'under_construction' => "static_pages#under_construction", as: "under_construction"

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :line_items, dependent: :destroy
  has_many :backups
  belongs_to :user, optional: true
  belongs_to :admin, optional: true
  has_many :wishlist_line_items, dependent: :destroy

  scope :report_between, ->(start_date, end_date) { where(created_at: start_date..end_date) }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?, except: [:index]
  before_action :delivery_only?, except: [:edit, :update]
  before_action :handle_update_status, only: [:update]

  def get_all_orders_report
    @orders = Order.where(status: true)
  end

  def seven_days_ago_report
    @orders = Order.where(sold_date: 7.days.ago)
  end

  def invoice
    @invoice = Order.find(params[:id])
  end

  def index
    @search_order = Order.ransack(params[:search])
    @orders = @search_order.result.where.not(:total_amount => 0.0).order(id: :desc).page(params[:page]).per(20)
  end

  def search
    index
    render :index
  end

  def show
    @order = Order.find(params[:id])
  end

  def new

  end

  def create
    @order = current_admin.orders.build(order_params)
    if @order.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_orders_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or order Duplicated"
        format.html { redirect_to admin_orders_path }
        format.js { render template: "admin/categories/order_error.js.erb" }
      end
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      @order.line_items.each do |item|
        if @order.status == true
          item.product.update_columns(remaining_stock_quantity: item.product.remaining_stock_quantity - item.quantity)
          if params[:order][:discount].to_i == 0.0 && params[:order][:delivery_fee].to_i == 0.0
            @order.update(profit: 0.0, discount: 0.0, delivery_fee: 0.0)
          elsif params[:order][:discount] != 0.0 && params[:order][:delivery_fee] != 0.0
            profit = (@order.sub_total.to_i - (params[:order][:discount].to_i + params[:order][:delivery_fee].to_i))
            @order.update(profit: profit, discount: params[:order][:discount], delivery_fee: params[:order][:delivery_fee])
          elsif params[:order][:discount] != 0.0
            profit = (@order.sub_total.to_i - params[:order][:discount].to_i)
            @order.update(profit: profit, discount: params[:order][:discount], delivery_fee: params[:order][:delivery_fee])
          elsif params[:order][:delivery_fee] != 0.0
            profit = (@order.sub_total.to_i - params[:order][:delivery_fee].to_i)
            @order.update(profit: profit, discount: params[:order][:discount], delivery_fee: params[:order][:delivery_fee])
          end
        end
      end
      respond_to do |format|
        flash.now[:notice] = "Successful Updated"
        format.html { redirect_to admin_orders_path }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @order = Order.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_orders_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def delivery_only?
      unless !current_admin.delivery?
        unless @admin == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def order_params
      params.required(:order).permit(:first_name, :last_name, :phone_num, :description, :status)
    end

    def handle_update_status
      @order = Order.find(params[:id])
      if @order.status == true
        respond_to do |format|
          format.html { redirect_to admin_orders_path }
          format.js { render template: "admin/orders/handle_update_status.js.erb" }
          flash.now[:alert] = "You cant do that!"
        end
      end
    end

end

app/controllers/orders_controller.rb
class OrdersController < FrontEndApplication
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :profile]
  before_action :cart_is_empty, only: [:new, :create]

  def profile
    @orders_status = current_user.orders.page(params[:page]).per(10).where("total_amount != 0")
    @categories = Category.all
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @items = current_cart.order.line_items
  end

  def new
    @search = Product.ransack(params[:search])
    @products = @search.result
    @order = current_cart.order
    @categories = Category.all
  end

  def create
    @order = current_cart.order(order_params)
    @order.update(user_id: current_user.id)
    client = Slack::Web::Client.new
    client.auth_test
    if @order.save
      @order.update(sold_date: Time.now, total_amount: @cart.sub_total)
      client.chat_postMessage(
        channel: '#preorder',
        text: "http://loyosja.com/admin/orders/#{@order.id}/edit",
        as_user: true
      )
      session[:cart_token] = nil
      redirect_to profiles_path
      flash[:notice] = "Thank for your order"
    else
      flash[:alert] = "Please fill the bill infomation"
      render :new
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to profiles_path
    flash[:notice] = "Order has been cancelled"
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(user_id: current_user.id)
    client = Slack::Web::Client.new
    client.auth_test
    if @order.update(order_params)
      @order.update(sold_date: Time.now, total_amount: current_cart.order.sub_total)
      client.chat_postMessage(
        channel: '#preorder',
        text: "http://loyosja.com/admin/orders/#{@order.id}/edit",
        as_user: true
      )
      session[:cart_token] = nil
      redirect_to profiles_path
      flash[:notice] = "Thank for your order"
    else
      flash[:alert] = "Please fill the bill infomation"
      render :edit
    end
  end

  def cart_is_empty
    return unless current_cart.items_count == 0
    flash[:alert] = "You cart is empty"
    redirect_to cart_path
  end

  private

    def order_params
      params.require(:order).permit(
        :user_id,
        :first_name,
        :last_name,
        :address_one,
        :description,
        :sold_date,
        :phone_num,
        line_items_attributes:[:id, :product_id]
      )
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_edit.html.erb
<%=content_tag :div, class: "modal fade modal-slide-right", id: "edit_#{dom_id(@order, :modal)}" do%>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-12">
            <h5 class="m-b-0" id="edit_user">Edit Order</h5>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body overflow-auto">
        <%=simple_form_for([:admin, @order], remote: true) do |f|%>
          <div class="form-row">
            <div class="form-group col-md-12">
              <label>First Name</label>
              <%=f.text_field :first_name, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label>Last Name</label>
              <%=f.text_field :last_name, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label>Phone Number</label>
              <%=f.text_field :phone_num, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label>Description</label>
              <%=f.text_area :description, class: "form-control", rows:"10"%>
            </div>
            <div class="form-group col-md-12">
              <label>Discount</label>
              <%=f.text_field :discount, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label>Delivery Fee</label>
              <%=f.text_field :delivery_fee, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label class="cstm-switch">
                <%=f.check_box :status, class: "cstm-switch-input"%>
                <span class="cstm-switch-indicator "></span>
              </label>
            </div>
            <div class="col-md-12">
              <div class="form-group">
                <%=f.submit "Update", class: "btn btn-primary", id: "order_submit"%>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
<%end%>

app/views/admin/orders/_filter_order.html.erb
<div class="card m-b-30 m-t-30">
  <div class="card-header">
    <div class="card-title">
      <h3>Reports</h3>
    </div>
  </div>
  <div class="card-body">

    <p class="text-muted ">Search By Date</p>

    <ul class="list-group">
      <%=search_form_for([:admin, @search_order], method: :get, remote: true) do |f|%>
        <div class="row">
          <div class="col-lg-6">
            <label for="">From</label>
            <%=f.text_field :sold_date_gteq, class: "form-control", id: "start_date" , placeholder: "Start Date"%>
          </div>
          <div class="col-lg-6">
            <label for="">To</label>
            <%=f.text_field :sold_date_lteq, class: "form-control", id: "end_date" , placeholder: "End Date"%>
          </div>
        </div>
        <div class="p-b-20">
          <hr>
          <%=f.submit "Search", class: "btn btn-primary btn-block"%>
          <%=link_to "Reset", admin_orders_path, class: "btn btn-warning btn-block", remote: true%>
        </div>
      <%end%>
    </ul>

  </div>
</div>

app/views/admin/orders/_order.html.erb
<%if order.sold_date != nil%>
  <tr class="delete_order_<%=order.id%>">
    <td id="data_<%=order.id%>">
      <%=order.id%>
    </td>
    <td>
      <%=number_to_currency(order.sub_total)%>
    </td>
    <td>
      <%=number_to_currency(order.line_items.sum('quantity * price'))%>
    </td>
    <td>
      <%=number_to_currency(order.profit)%>
    </td>
    <%if order.status != true %>
      <td>
        <span class="badge badge-danger"><%=status_converter(order.status, correct: "Delivered", incorrect: "In Progress")%></span>
      </td>
    <%else%>
      <td >
        <span class="badge badge-success"><%=status_converter(order.status, correct: "Delivered", incorrect: "In Progress")%></span>
      </td>
    <%end%>
    <td>
      <%=order.sold_date%>
    </td>
    <td>
      <%=time_ago(order.updated_at)%>
    </td>
    <td class="text-center">
      <%=form_for([:admin, order], remote: true) do |f|%>
        <%=link_to admin_order_path(order), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
          View
        <%end%>
        <%=link_to edit_admin_order_path(order),id: "link_#{order.id}",class: "btn btn-primary", remote: true do %>
          Edit
        <% end %>
      <%end%>
    </td>
  </tr>
<%end%>

app/views/admin/orders/_show.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "detail_#{dom_id(@order, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg modal-xxl" role="document">
     <div class="modal-content">
        <div class="modal-header">
           <h5 class="modal-title" id="myLargeModalLabel">Large Modal</h5>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
           </button>
        </div>
        <div class="modal-body">
           <div class="bg-dark m-b-30">
              <div class="container">
                 <div class="row p-b-60 p-t-60">
                    <div class="col-md-6 text-white p-b-30">
                       <div class="media">
                          <div class="avatar avatar mr-3">
                             <div class="avatar-title bg-success rounded-circle mdi mdi-receipt  "></div>
                          </div>
                          <div class="media-body">
                             <div class="opacity-75">To,</div>
                             <h4 class="m-b-0"><%=@order.address_one%>
                            <p>Customer Name: <%=@order.first_name %> <%=@order.last_name%></p>
                            <p>Phone: <%=@order.user.phone_number %></p>
                             </h4>
                             <p class="opacity-75">
                                Invoice ID <span>#00<%=@order.id%></span>
                                <br>
                                Invoice Date : <%=@order.created_at%>
                             </p>
                             <button class="btn btn-white-translucent" id="printDiv">
                             <i class="mdi
                                mdi-printer"></i>
                             Print</button>
                          </div>
                       </div>
                    </div>
                    <div class="col-md-5 text-center m-b-30 ml-auto">
                       <div class="rounded text-white bg-white-translucent">
                          <div class="p-all-15">
                             <div class="row">
                                <div class="col-md-6 my-2 m-md-0">
                                   <div class="text-overline    opacity-75">amount received</div>
                                   <h3 class="m-0 text-success"><%=number_to_currency(@order.line_items.sum('quantity * price'))%></h3>
                                </div>
                                <div class="col-md-6 my-2 m-md-0">
                                   <div class="text-overline    opacity-75">amount pending</div>
                                   <h3 class="m-0 text-danger"><%=number_to_currency(@order.line_items.sum('quantity * price'))%></h3>
                                </div>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
           <div class="pull-up">
              <div class="container" id="printableArea">
                 <div class="row">
                    <div class="col-md-12 m-b-40">
                       <div class="card">
                          <div class="card-body">
                             <div class="row">
                                <div class="col-md-6">
                                   <img src="assets/img/logos/nytimes.jpg" width="60" class="rounded-circle" alt="">
                                   <address class="m-t-10">
                                      To,<br>
                                      <span class="h4 font-primary">
                                      <%=@order.address_one%>
                                      </span>
                                   </address>
                                </div>
                                <div class="col-md-6 text-right my-auto">
                                   <h1 class="font-primary">INVOICE</h1>
                                   <div class="">Invoice Number: <span>#00<%=@order.id%></span></div>
                                   <div class="">Date: <%=@order.created_at%></div>
                                </div>
                             </div>
                             <div class="table-responsive ">
                                <table class="table m-t-50">
                                   <thead>
                                      <tr>
                                         <th class="">Products</th>
                                         <th class="text-center">QTY</th>
                                         <th class="text-center">Unit Price</th>
                                         <th class="text-right">Sub Total</th>
                                      </tr>
                                   </thead>
                                   <tbody>
                                      <%@order.line_items.each do |item|%>
                                      <tr>
                                         <td class="">
                                            <p class="text-black m-0">
                                              <%=item.product.product_name.capitalize%>
                                              (
                                              <%if item.color.present?%>
                                                <strong>Color: <%=item.color%></strong>,
                                                <strong>Size: <%=item.shirt_size%></strong>
                                              <%end%>
                                              )
                                            </p>
                                         </td>
                                         <td class="text-center"><%=item.quantity%></td>
                                         <td class="text-center"><%=number_to_currency(item.product.product_price)%></td>
                                         <td class="text-right"><%=number_to_currency(@order.line_items.sum('quantity * price'))%></td>
                                      </tr>
                                      <%end%>
                                      <tr>
                                         <td colspan="3" class="text-right">
                                            Sub Total
                                         </td>
                                         <td colspan="2" class="text-right">
                                            <%=number_to_currency(@order.line_items.sum('quantity * price'))%>
                                         </td>
                                      </tr>
                                      <tr>
                                         <td colspan="3" class="text-right">
                                            Discount
                                         </td>
                                         <td colspan="2" class="text-right">
                                            0.0
                                         </td>
                                      </tr>
                                      <tr class="">
                                         <td colspan="3" class="text-right">
                                            Taxes
                                         </td>
                                         <td colspan="2" class="text-right">
                                            $ 0.0
                                         </td>
                                      </tr>
                                      <tr class="bg-light">
                                         <td colspan="3" class="text-right">
                                            Total
                                         </td>
                                         <td colspan="2" class="text-right">
                                            <%=number_to_currency(@order.line_items.sum('quantity * price'))%>
                                         </td>
                                      </tr>
                                   </tbody>
                                </table>
                             </div>
                             <div class="p-t-10 p-b-20">
                                <p class="text-muted ">
                                   <%=@order.description%>
                                </p>
                                <hr>
                                <div class="text-center opacity-75">
                                   &copy; loyosja.com 2019
                                </div>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-dismiss="modal">
           Close
           </button>
           <button type="button" class="btn btn-primary">Save changes</button>
        </div>
     </div>
  </div>
<%end%>

app/views/admin/orders/destroy.js.erb
$('.delete_order_<%=@order.id%>').remove();

app/views/admin/orders/edit.js.erb
$('body').append('<%= j render partial: "admin/orders/edit"%>');
$('#edit_<%= dom_id @order, :modal%>').modal('toggle');
$('tr').find('td:nth-child(3)').each(function(){
  if ($(this).text().trim().replace(/ +/g, "") == "<%=status_converter(@order.status).gsub(/\s+/, '')%>") {
    $(this).parent().addClass("edit_row_<%=@order.id%>")
  }
});

app/views/admin/orders/handle_update_status.js.erb
$("#handle_update_status-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/orders/index.html.erb
<div id="handle_update_status-success"></div>
<div id="order-success"></div>
<%=render "admin/shared/aside"%>
<main class="admin-main">
   <!--site header begins-->
   <%=render "admin/shared/header"%>
   <!--site header ends -->
   <section class="admin-content">
      <div class="container-fluid">
      <!-- Content -->
      <div class="row">
         <div class="col-md-8">
            <div class="card m-b-30 m-t-30">
               <div class="card-header">
                  <h5 class="m-b-0">
                     <i class="mdi mdi-checkbox-intermediate"></i> Orders
                  </h5>
                  <h5 class="m-b-0 float-right">
                    <p>Total Amount: <%=total_order(@orders)%></p>
                    <p>Profit From (10-22-2019): <%=number_to_currency(@orders.sum('profit'))%></p>
                  </h5>
               </div>
               <div class="card-body">
                  <div class="table-responsive">
                     <table id="" class="table table-hover align-td-middle">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Sub Total</th>
                              <th>Total</th>
                              <th>Profit</th>
                              <th>Status</th>
                              <th>Sold Date</th>
                              <th>Updated_At</th>
                              <th class="text-center">Action</th>
                           </tr>
                        </thead>
                        <tbody id="orders">
                         <%= render @orders%>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-lg-12">
                <nav>
                  <%= paginate @orders, window: 2 %>
                </nav>
              </div>
            </div>
            <%= link_to "Get All Orders Report", admin_get_all_orders_report_path(format: "xlsx"), class: "btn btn-primary m-b-30" %>
            <%= link_to "7 days ago", admin_seven_days_ago_report_path(format: "xlsx"), class: "btn btn-primary m-b-30"%>
         </div>
         <div class="col-md-4">
           <%=render "filter_order"%>
         </div>
      </div>
      <!-- Modal -->
   </section>
</main>

app/views/admin/orders/index.js.erb
$('#orders').html("<%=j render(@orders)%>")

app/views/admin/orders/order_error.js.erb
$("#order-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/orders/order_success.js.erb
$("#admin-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/orders/show.js.erb
$('body').append('<%= j render partial: "admin/orders/show"%>');
$('#detail_<%= dom_id @order, :modal%>').modal('toggle');

app/views/admin/orders/update.js.erb
$("#order-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");
$(".edit_row_<%=@order.id%>").find('td:nth-child(3)').text("<%=order_status_converter(@order.status)%>").next().text("<%=time_ago(@order.created_at)%>").next().text("<%=time_ago(@order.updated_at)%>")
$('.delete_order_<%=@order.id%>').remove();