config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'
    resources :home

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      get 'invoices/:id' => 'orders#invoice', as: "invoice"
      get "get_all_orders_report" => "orders#get_all_orders_report"
      get "seven_days_ago_report" => "orders#seven_days_ago_report"
      get "reports" => "reports#index"

      resources :products do
        collection do
          patch :sort
          get "sort_product" => "products#sort_product", as: "sort_product"
          get "sort_product_featured" => "products#sort_product_featured", as: "sort_product_featured"
        end
      end



      resources :categories
      resources :sub_categories
      resources :product_types
      resources :galleries
      resources :orders do
        collection do
          get "search" => "orders#search", vai: [:get, :post], as: :search
        end
      end
      resources :users
      resources :admins
      resources :line_items
      resources :settings, only: [:index, :new, :update, :create, :edit]

      get "testorder" => "orders#testorder"
    end

    resources :sub_categories, only: [:show]
    resources :categories, only: [:show]
    resources :wishlists
    resources :products do
      resources :reviews
    end

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations",
      omniauth_callbacks: "users/omniauth_callbacks",
      passwords: 'users/passwords'
    }

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    resources :orders do
      delete "cancel/:id" => "line_items#cancel_item", as: "cancel_line_item"
      post "update_quantity/:id" => "line_items#update_quantity", as: "update_quantity"
    end
    resources :product_types, only: [:index, :show]
    resources :types, only: [:show]
    get 'profiles' => "orders#profile", :as => "profiles"
    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'
    get 'abouts' => "static_pages#about", :as => "abouts"
    get 'deliveries' => "static_pages#delivery", :as => "deliveries"
    get 'cancellation' => "static_pages#cancellation", :as => "cancellation"

    get 'cart' => "line_items#index"
    get 'history' => "line_items#history", :as => "history"
    resources :line_items, path: "/cart/items"
    get  'cart/checkout' => "orders#new", :as => "checkout"
    patch 'cart/checkout' => "orders#create"
    get 'under_construction' => "static_pages#under_construction", as: "under_construction"

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category, optional: true
  has_many :products
  has_many :sub_categories, through: :products

  belongs_to :admin
  before_save :update_slug
  validates :sub_category_name,
             uniqueness: { case_sensitive: true },
             presence: true,
             length: { maximum: 20 }


  def update_slug
    self.slug = sub_category_name.parameterize
  end

end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?, except: [:index]
  before_action :delivery_only?

  def index
    @sub_category = current_admin.sub_categories.build
    @sub_categories = SubCategory.all.order(id: :desc)
  end

  def show
    @sub_category = SubCategory.find(params[:id])
  end

  def new

  end

  def create
    @sub_category=current_admin.sub_categories.build(sub_category_params)
    if @sub_category.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_sub_categories_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or sub category Duplicated"
        format.html { redirect_to admin_sub_categories_path }
        format.js { render template: "admin/sub_categories/sub_category_error.js.erb" }
      end
    end
  end

  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  def update
    @sub_category = SubCategory.find(params[:id])
    if @sub_category.update(sub_category_params)
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_sub_categories_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or sub category Duplicated"
        format.html { redirect_to admin_sub_categories_path }
        format.js { render template: "admin/sub_categories/sub_category_error.js.erb" }
      end
    end
  end

  def destroy
    @sub_category = SubCategory.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_sub_categories_url }
      format.js
    end
  end


  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def delivery_only?
      unless !current_admin.delivery?
        unless @admin == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def sub_category_params
      params.required(:sub_category).permit!
    end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < FrontEndApplication
  def show
    @subcategory = SubCategory.find_by_slug(params[:id])
    @products_sub = @subcategory.products.order(id: :desc).page(params[:page]).per(12)
  end
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/views/sub_categories/show.html.erb
<%title"#{@subcategory.sub_category_name} | loyosja.com"%>
<%meta_description "An online gift shop for awesome people. At Loyosja, we offer you only the awesome and unique gifts for your special occassions. Explore the collection of amazing products to surprise your loved one and make your special day even more special."%>
<%image_og "https://loyosja.com/images/loyosjaseosearchimage.png"%>
<div id="wishlist_line_item-errors"></div>
<div id="wishlist_line_item-success"></div>
<!-- Preloader -->
<div id="preloader" class="preloader">
   <div class="loader-cube">
      <div class="loader-cube__item1 loader-cube__item"></div>
      <div class="loader-cube__item2 loader-cube__item"></div>
      <div class="loader-cube__item4 loader-cube__item"></div>
      <div class="loader-cube__item3 loader-cube__item"></div>
   </div>
</div>
<!-- End Preloader -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<!-- WRAPPER -->
<!-- ––––––––––––––––––––––––––––––––––––––––– -->
<div id="pageWrapper" class="page-wrapper">
<!-- –––––––––––––––[ HEADER ]––––––––––––––– -->
<header id="mainHeader" class="main-header">
   <!-- Top Bar -->
   <%=render "front-end/topbar"%>
   <!-- End Top Bar -->
   <!-- Header Header -->
   <%=render "front-end/header"%>
   <!-- End Header Header -->
   <!-- Header Menu -->
   <%=render "front-end/header-menu"%>
   <!-- End Header Menu -->
</header>
<!-- –––––––––––––––[ HEADER ]––––––––––––––– -->
<!-- –––––––––––––––[ PAGE CONTENT ]––––––––––––––– -->
<main id="mainContent" class="main-content">
   <div class="page-container">
     <div class="container">
      <section class="section latest-deals-area ptb-30">
        <header class="panel ptb-15 prl-20 pos-r mb-30">
          <h3 class="section-title font-18 t-uppercase" style="text-align: center;">
            <b class="line-bottom"><%=params[:id].tr('-', ' ').capitalize %></b>
          </h3>
        </header>
        <div class="row row-masnory row-tb-20">
          <%@products_sub.each do |product|%>
            <div class="col-xs-6 col-sm-4 col-lg-3" >
              <div class="deal-single">
                <%product.assets.limit(1).order(id: :asc).each do |asset|%>
                  <%=link_to new_product_review_path(product.slug) do%>
                    <figure class="deal-thumbnail embed-responsive embed-responsive-16by9" style="padding-bottom: 95.25%;">
                      <img src="<%=asset.image%>">
                    </figure>
                  <%end%>
                <%end%>
                <div class="bg-white pt-20">
                  <div class="pr-md-10">
                    <h3 class="deal-title mb-10 text-center"style="font-size:15px; font-weight:bold;" title="<%=product.product_name%>">
                      <%=link_to first_cap_letter(product.product_name).truncate(20), new_product_review_path(product.slug)%>
                    </h3>
                  </div>
                  <div class="deal-price pos-r mb-15">
                    <h3 class="price ptb-5 text-center">
                      <ul class="deal-meta list-inline mb-10 color-mid text-center"style="font-size:14px;">
                        <span id="heart-<%=product.id%>"></span>

                          <%=number_to_currency(product.product_price)%>

                        <%if user_signed_in?%>
                          <li>
                            <%=button_to wishlist_line_items_path(:product_id => product.id), params:{productID: product.id},class: "btn-heart", remote: true do %>
                              <i class="ico fa fa-heart" style="color: #e67e22"></i>
                            <% end %>
                          </li>
                          <li>
                            <%=link_to product, remote: true do %>
                              <i class="fa fa-camera" style="color: #e67e22"></i>
                            <% end %>
                          </li>
                        <%else%>
                          <li>
                            <%=button_to wishlist_line_items_path(:product_id => product.id), params:{productID: product.id},class: "btn-heart" do %>
                              <i class="ico fa fa-heart" style="color: #e67e22"></i>
                            <% end %>
                          </li>
                          <li>
                            <%=link_to product, remote: true do %>
                              <i class="fa fa-camera" style="color: #e67e22"></i>
                            <% end %>
                          </li>
                        <%end%>
                      </ul>
                    </h3>
                  </div>
                  <hr>
                </div>
              </div>
            </div>
          <%end%>
        </div>

        <div class="row">
          <div class="col-xs-12 col-lg-12">
            <div class="load-more-container">
              <%= paginate @products_sub, window: 2 %>
            </div>
          </div>
        </div>
      </section>
   </div>
   </div>
</main>
<%=render "front-end/footer-area"%>

<div id="backTop" class="back-top is-hidden-sm-down">
   <i class="fa fa-angle-up" aria-hidden="true"></i>
</div>

app/views/sub_categories/test.html.erb
<div class="container hidden-xs">
   <section class="section latest-coupons-area ptb-30 hidden-lg hidden-md hidden-xs hidden-xxs">
      <header class="ptb-15 prl-20 pos-r mb-30">
         <h3 class="section-title font-18">Gift</h3>
         <a class="btn btn-o btn-xs pos-a right-10 pos-tb-center">View All</a>
      </header>
      <div class="latest-coupons-slider owl-slider" data-autoplay-hover-pause="true" data-loop="true" data-autoplay="true" data-smart-speed="1000" data-autoplay-timeout="10000" data-margin="30" data-nav-speed="false" data-items="1"
         data-xxs-items="1" data-xs-items="2" data-sm-items="2" data-md-items="3" data-lg-items="4">
         <%@subcategory.products.each do |product|%>
         <div class="coupon-item">
            <div class="coupon-single panel t-center">
               <div class="ribbon-wrapper is-hidden-xs-down">
                  <div class="ribbon">Featured</div>
               </div>
               <div class="row row-masnory row-tb-20">
                  <div class="col-sm-12 col-lg-12">
                     <div class="deal-single panel">
                        <%product.assets.limit(1).order(id: :asc).each do |asset|%>
                        <figure class="deal-thumbnail embed-responsive embed-responsive-16by9" data-bg-img="<%=asset.image%>" ​="​" style="padding-bottom: 95.25%;"></figure>
                        <%end%>
                        <div class="bg-white pt-20 pl-20 pr-15">
                           <div class="pr-md-10">
                              <h3 class="deal-title mb-10 text-left">
                                 <a href="deal_single.html"><%=product.product_name%></a>
                              </h3>
                             <!--  <ul class="deal-meta list-inline mb-10 color-mid text-left">
                                 <li><i class="ico fa fa-map-marker mr-10"></i>United State</li>
                                 <li><i class="ico fa fa-shopping-basket mr-10"></i>120 Bought</li>
                              </ul> -->
                           </div>
                           <div class="deal-price pos-r mb-15">
                              <h3 class="price ptb-5 text-left">
                                 <ul class="deal-meta list-inline mb-10 color-mid text-right">
                                    <span id="heart-coupon-<%=product.id%>"></span>
                                    <span class="mar4-ip678">
                                    <%=number_to_currency(product.product_price)%>
                                    </span>
                                    <%if user_signed_in?%>
                                    <li>
                                       <%=button_to wishlist_line_items_path(:product_id => product.id), params:{productID: product.id},class: "btn-heart", remote: true do %>
                                       <i class="ico fa fa-heart" style="color: #e67e22"></i>
                                       <% end %>
                                    </li>
                                    <li>
                                       <%=link_to product, remote: true do %>
                                       <i class="fa fa-camera" style="color: #e67e22"></i>
                                       <% end %>
                                    </li>
                                    <%else%>
                                    <li>
                                       <%=button_to wishlist_line_items_path(:product_id => product.id), params:{productID: product.id},class: "btn-heart" do %>
                                       <i class="ico fa fa-heart" style="color: #e67e22"></i>
                                       <% end %>
                                    </li>
                                    <li>
                                       <%=link_to product, remote: true do %>
                                       <i class="fa fa-camera" style="color: #e67e22"></i>
                                       <% end %>
                                    </li>
                                    <%end%>
                                 </ul>
                              </h3>
                           </div>
                           <hr>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- end row -->
            </div>
         </div>
         <%end%>
      </div>
   </section>
</div>
<!-- ------------------- -->